import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="retro">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="w-full  flex justify-center  ">
          <nav className="w-[30%] h-[10%]  rounded-4xl shadow-lg shadow-gray-700  flex p-1">
            {/* <h1 className="text-2xl font-extrabold">Counter</h1> */}
            <div className="w-full flex justify-center">
              <Link href={"/"} className="text-[1rem] font-semibold ml-6">
                Home
              </Link>

              <Link href={"/"} className="text-[1rem] font-semibold ml-6">
                help
              </Link>
            </div>
          </nav>
        </div>

        <ToastContainer position="top-right" autoClose={500} />
      </body>
    </html>
  );
}
